spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://47.99.74.206:3306/gu_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: product
  application:
    name: product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 300000
      cache-null-values: true
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: show_status  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
server:
  port: 7100
logging:
  level:
    com.product: error
mall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

