spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: order
    alibaba:
      seata:
        tx-service-group: happy_order_group
    sentinel:
      transport:
        dashboard: localhost:8333
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://47.99.74.206:3306/gu_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  application:
    name: order
  rabbitmq:
    host: 47.99.74.206
    port: 5672
    virtual-host: /
    publisher-confirm-type: simple
    publisher-returns: true
    template:
      mandatory: true    #只要抵达队列，以异步发送优先回调这个 returnconfirm
    listener:
      simple:
        acknowledge-mode: manual     # 手动 ack 消息
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  session:
    store-type: redis
  redis:
    port: 6379
    host: localhost
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 20000
mall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
