spring:
  application:
    name: seckill
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: seckill
  redis:
    host: localhost
    port: 6379
  task:
    execution:
      pool:
        core-size: 5
        max-size: 50
  session:
    store-type: redis
server:
  port: 18000
