spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: cart
  application:
    name: cart
  thymeleaf:
    cache: false
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
server:
  port: 17000
