spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: third
    sentinel:
      transport:
        dashboard: localhost:8333
  application:
    name: third

server:
  port: 13000

