spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: third
  application:
    name: third

server:
  port: 13000

alibaba:
  cloud:
    access-key: LTAI5tHRWqMKb6ZPhds8hNBv
    secret-key: gUsOhCHLthZ373mbRNzZI6B9jjzNqv
    oss:
      endpoint: oss-cn-hangzhou.aliyuncs.com
