spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: elasticSearch
    sentinel:
      transport:
        dashboard: localhost:8333
  application:
    name: elasticSearch
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    port: 6379
    host: localhost
server:
  port: 15000
